"""In flaskcards table column name Key changed to key

Revision ID: 53b23ed7f8ee
Revises: ac7dfb5f9068
Create Date: 2025-03-11 21:34:36.635442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53b23ed7f8ee'
down_revision = 'ac7dfb5f9068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_index('ix_Flashcard_Key')
        batch_op.create_index(batch_op.f('ix_Flashcard_key'), ['key'], unique=False)
        batch_op.drop_column('Key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Key', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_Flashcard_key'))
        batch_op.create_index('ix_Flashcard_Key', ['Key'], unique=False)
        batch_op.drop_column('key')

    # ### end Alembic commands ###
