"""Added key_headers and value_headers columns to Flashcard_packs table

Revision ID: 7ace6ae65c72
Revises: 53b23ed7f8ee
Create Date: 2025-03-15 17:31:39.964053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ace6ae65c72'
down_revision = '53b23ed7f8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Flashcard_pack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('value_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Flashcard_pack', schema=None) as batch_op:
        batch_op.drop_column('value_headers')
        batch_op.drop_column('key_headers')

    # ### end Alembic commands ###
