"""Changed Flashcards table value column type to JSONB

Revision ID: ac7dfb5f9068
Revises: d1badeac0cce
Create Date: 2025-03-08 19:02:34.589622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac7dfb5f9068'
down_revision = 'd1badeac0cce'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('Flashcard', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="value::jsonb")  # Explicit cast



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Flashcard', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
