version: "3.8"

services:
  db:
    image: postgres:17
    container_name: flashcard_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flashcard_app
    restart: always
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      DATABASE_URL_WEB: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "5000:5000"

volumes:
  postgres_data:
