# Use an official lightweight Python image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP run.py
ENV FLASK_ENV production

# Set the working directory in the container
WORKDIR /app

# Copy required files
COPY requirements.txt ./
COPY app/ app/
COPY run.py ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Flask runs on
EXPOSE 5000

# Start the Flask application
CMD ["gunicorn", "-b", "0.0.0.0:5000", "run:app"]
