version: "3.8"

services:
  db:
    image: postgres:17
    container_name: flashcard_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", postgres ]
      interval: 10s
      retries: 5

  web:
    build: .
    container_name: flashcard_app
    restart: always
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      DATABASE_URL_WEB: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    command: >
      sh -c "flask db upgrade && gunicorn -w 4 -b 0.0.0.0:5000 run:app"
    ports:
      - "5000:5000"

volumes:
  postgres_data:
